updated compile like compile32

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -1,33 +1,43 @@
 #!/bin/bash
 
-if [ $# -lt 1 ]; then
-    echo "no argument given";
-    exit 1;
-fi
+usage="Usage: $(basename $0) [-dh] filename\n
+        -d              delete the (temporary) header file\n
+        -h              display help (this screen)\n\n
+        example:        "$(basename $0)" -d main\n
+        notice the filename without extension!"
 
-if [ $1 = "--help" ]; then
-    clear;
-    echo "this script compiles assembly files in the x64 format using nasm"
-    echo "[--help] - displays this screen"
-    echo " usage: compile [filename] [-y]"
-    echo " -y		delete header file (temporary)"
-    echo "example: compile main -y"
-    exit 1;
-fi
+errmsg="You have to specify a file!"
 
 MYPWD=${PWD}
 
-if [ -f "$MYPWD/$1.asm" ]; then
+dswitch=false
+hswitch=false
+exitcode=0
+
+while getopts "dh" option; do
+ case $option in
+  d)
+   dswitch=true
+   ;;
+  h)
+   hswitch=true
+   ;;
+  \?)
+   echo "invalid option -$OPTARG"
+   hswitch=true
+   exitcode=1
+ esac
+done
+
+shift $((OPTIND - 1))
+filename="$1"
+
+if [ "$hswitch" = true ]; then
+        echo -e $usage
+        exit $exitcode
+fi
+
+if [ -e "$filename.asm" ]; then
     nasm -f elf64 -o "$MYPWD/$1.o" "$MYPWD/$1.asm";
     ld -o "$MYPWD/$1" "$MYPWD/$1.o";
-fi
-if [ $# -eq 2 ]; then
-    if [ $2 = "-y" ]; then
-	\rm -f "$MYPWD/$1.o";
-    else
-	echo "wrong input"
-    fi
-fi
-if [ $# -gt 2 ]; then
-    echo "too many arguments";
 fi
